const mongoose = require("../config/db.config");
const { Schema } = mongoose;

const postSchema = new Schema({
    _id: { type: String, unique: true },
    title: {
        type: String,
        required: true,
        trim: true

    },
    body: {
        type: String,
        required: true,
        trim: true
    },
    comment: {
        type: String,
        trim: true
    }
},{ timestamps:true });

postSchema.methods.toJSON = function () {
    const obj = this.toObject({versionKey:false}); // versionKey: false prevents the version key generated by mongodb to be displayed in the response sent.
    return obj
}

const post = mongoose.model('post', postSchema);
module.exports = post